### ISSUE TITLE
"Gradient obfuscation" is just the well-known "gradient masking" phenomenon

### ISSUE THREAD

**Issue by goodfeli** [anishathalye/obfuscated-gradients#2] opened 2018-02-02 06:45 UTC
This paper claims to have identified the "gradient obfuscation" problem. "Gradient obfuscation" is just a different name for the well-known "gradient masking" problem:
https://arxiv.org/abs/1602.02697
https://blog.openai.com/adversarial-example-research/
https://arxiv.org/pdf/1705.07204.pdf
https://seclab.stanford.edu/AdvML2017/slides/17-09-aro-aml.pdf

Though you claim to have studied "all defenses" accepted to ICLR 2018, you have omitted one defense that specifically addresses the gradient masking problem: https://openreview.net/forum?id=rkZvSe-RZ

**Comment by carlini** [comment] 2018-02-02 07:55
I wasn't really sure if we should call it gradient masking or not. At the end, my main argument against calling it gradient masking is that what's being done here seems somewhat different.

I think of gradient masking as something that's caused by, e.g., distillation or, as you find, training against FGSM (without random addition), where the gradient points the wrong way only locally, but the majority of the gradient signal is still preserved.

In the case of the defenses we were looking at, the gradients are usually complicated everywhere, and at almost no point do anything useful to point to the actual adversarial direction.

I don't know. Maybe it was the wrong decision. But I somehow feel that having two closely related words is less bad than taking a word with one meaning, and expanding its definition to a new one. If researchers decide that what we've done is wrong and want to call it gradient masking, I would be fine with that. The exact word used is less important to me than the understanding of what is happening.

You're definitely right though that we should have put this discussion in the paper to clarify it, though -- we'll make this correction. It was an oversight and we obviously should have wrote about this in retrospect. Florian also discussed this with us today (my reply here is largely copied from the email I sent him). 

We do not evaluate ensemble adversarial training because it does not argue white-box security. We state this in the paper but per #1 we make the incorrect claim in the abstract that we examine all defenses, that will be fixed in an updated copy of our paper over the next day or two.

**Comment by goodfeli** [comment] 2018-02-02 10:25
https://arxiv.org/abs/1602.02697 defines gradient masking as a defense that results in a " a model
that does not have useful gradients". This is general enough to cover every use of "obfuscated gradients" in your paper, and the definition you offer in this response ("In the case of the defenses we were looking at, the gradients are usually complicated everywhere, and at almost no point do anything useful to point to the actual adversarial direction."). We give specific examples like nearest neighbor classifiers that have very small gradients but we don't restrict the definition of "useful" to small. Our specific examples come from a broader category than what you list above (gradient masking caused by distillation or training on FGSM).

https://blog.openai.com/adversarial-example-research repeats the definition in terms of a "useful gradient."

https://arxiv.org/pdf/1705.07204.pdf  shows specifically plots of how large, non-zero gradients may not characterize the global loss well.

https://seclab.stanford.edu/AdvML2017/slides/17-09-aro-aml.pdf again uses 3D plots to describe loss surfaces that can mislead relatively complicated optimizers without having the correct decision boundary.

https://medium.com/onfido-tech/adversarial-attacks-and-defences-for-convolutional-neural-networks-66915ece52e7 defines gradient masking as "in these kind of defences, a perturbation in the gradients is introduced, making the white box attacks less effective, but the decision boundary remains mostly unchanged after the adversarial training."


You also use "obfuscated gradients" to describe several cases that clearly fall under the most restrictive possible interpretation of "gradient masking", such as thermometer coding where the gradient on the real-valued input is exactly zero.

**Comment by rockkingjy** [comment] 2018-02-04 03:04
Interesting.

**Comment by heyang9** [comment] 2018-02-07 13:00
Interesting XD

**Comment by szrlee** [comment] 2018-02-08 02:57
Interesting 👍

**Comment by anishathalye** [comment] 2018-02-08 03:02
It looks like this is turning into a spam thread. We have discussed / are discussing this with Ian directly. I'm going to close this thread to avoid further spam.

If anyone has anything to add to the discussion, feel free to email me and Nicholas.

**Closed by anishathalye** 2018-02-08 03:02 UTC
